/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Valentina
 */
public class Intento extends JFrame{
   
    public Intento() {
        initComponents();
       
        
    }
   
//    public void actionPerformed(ActionEvent evt){
//        if(evt.getSource()==porContribuyente){
//            MenuPorContribuyentes frame = new MenuPorContribuyentes();
//            frame.setVisible(true);
//        }else if(evt.getSource()==porAgencia){
//            MenuPorAgencia frame = new MenuPorAgencia();
//            frame.setVisible(true);
//        }else if(evt.getSource()==vehiculo){
//            MenuVehiculo frame = new MenuVehiculo();
//            frame.setVisible(true);
//        }else if(evt.getSource()==contribuyente){
//            MenuContribuyente frame = new MenuContribuyente();
//            frame.setVisible(true);
//        }else {
//            MenuVehiculoAContribuyente frame = new MenuVehiculoAContribuyente();
//            frame.setVisible(true);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Calcular = new javax.swing.JMenu();
        porContribuyente = new javax.swing.JMenuItem();
        porAgencia = new javax.swing.JMenuItem();
        Agregar = new javax.swing.JMenu();
        contribuyente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        vehiculoAcontribuyente = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Calcular.setText("Calcular");

        porContribuyente.setText("Por Contribuyente");
        porContribuyente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porContribuyenteActionPerformed(evt);
            }
        });
        Calcular.add(porContribuyente);

        porAgencia.setText("Por Agencia");
        porAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porAgenciaActionPerformed(evt);
            }
        });
        Calcular.add(porAgencia);

        jMenuBar1.add(Calcular);

        Agregar.setText("Agregar");

        contribuyente.setText("Contribuyente");
        contribuyente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contribuyenteActionPerformed(evt);
            }
        });
        Agregar.add(contribuyente);

        jMenuItem1.setText("Vehiculo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Agregar.add(jMenuItem1);

        vehiculoAcontribuyente.setText("Vehiculo a Contribuyente");
        vehiculoAcontribuyente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiculoAcontribuyenteActionPerformed(evt);
            }
        });
        Agregar.add(vehiculoAcontribuyente);

        jMenuBar1.add(Agregar);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contribuyenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contribuyenteActionPerformed
        MenuContribuyente frame = new MenuContribuyente();
        frame.setVisible(true);
    }//GEN-LAST:event_contribuyenteActionPerformed

    private void vehiculoAcontribuyenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiculoAcontribuyenteActionPerformed
        MenuVehiculoAContribuyente frame = new MenuVehiculoAContribuyente();
        frame.setVisible(true);
    }//GEN-LAST:event_vehiculoAcontribuyenteActionPerformed

    
    private void porAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porAgenciaActionPerformed
        MenuPorAgencia frame = new MenuPorAgencia();
        frame.setVisible(true);
    }//GEN-LAST:event_porAgenciaActionPerformed

    private void porContribuyenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porContribuyenteActionPerformed
        MenuPorContribuyentes frame;
        try {
            frame = new MenuPorContribuyentes();
            frame.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(Intento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_porContribuyenteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MenuVehiculo frame = new MenuVehiculo();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_SalirActionPerformed
    
    
     
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intento().setVisible(true);
               
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Agregar;
    private javax.swing.JMenu Calcular;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenuItem contribuyente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem porAgencia;
    private javax.swing.JMenuItem porContribuyente;
    private javax.swing.JMenuItem vehiculoAcontribuyente;
    // End of variables declaration//GEN-END:variables
}
